<?php

return [
    'bruteforce' => [
        'username_protection_enabled' => env('BF_USERNAME_ENABLED', true),
        'username_period_minutes'     => env('BF_USERNAME_PERIOD', 10),
        'username_max_failures'       => env('BF_USERNAME_MAX', 5),
        'username_protect_local_only' => env('BF_USERNAME_LOCAL_ONLY', false),
        'username_protect_admin'      => env('BF_USERNAME_PROTECT_ADMIN', true),
        'ip_protection_enabled'       => env('BF_IP_ENABLED', true),
        'ip_period_minutes'           => env('BF_IP_PERIOD', 10),
        'ip_max_failures'             => env('BF_IP_MAX', 10),
        'ip_block_at_firewall'        => env('BF_IP_FIREWALL', false),
        'ip_block_duration'           => env('BF_IP_DURATION', 'one_day'),
        'ip_max_before_one_day'       => env('BF_IP_MAX_ONE_DAY', 20),
        'ip_one_day_block_firewall'   => env('BF_IP_ONE_DAY_FIREWALL', false),
        'retain_failed_logins_minutes' => env('BF_RETAIN_MINUTES', 10),
        'auto_whitelist_threshold'    => env('BF_WHITELIST_THRESHOLD', 5),
        'notify_admin_on_unknown_ip'  => env('BF_NOTIFY_UNKNOWN_IP', true),
        'notify_admin_on_known_netblock' => env('BF_NOTIFY_KNOWN_NETBLOCK', false),
        'notify_admin_on_bruteforce_detect' => env('BF_NOTIFY_BRUTEFORCE', true),
    ],
    'cors' => ['allowed_origins' => [env('APP_URL', 'http://localhost')]],
    'rate_limits' => ['api' => '60,1', 'auth' => '10,1', 'public' => '120,1', 'contact' => '5,1', 'upload' => '20,1'],
    'headers' => [
        'x_frame_options'        => 'DENY',
        'x_content_type_options' => 'nosniff',
        'x_xss_protection'       => '1; mode=block',
        'referrer_policy'        => 'strict-origin-when-cross-origin',
        'permissions_policy'     => 'camera=(), microphone=(), geolocation=()',
        'hsts'                   => 'max-age=31536000; includeSubDomains; preload',
        'csp_enabled'            => env('CSP_ENABLED', true),
    ],
    'sanitization' => [
        'strip_tags'       => true,
        'trim_whitespace'  => true,
        'escape_html'      => true,
        'max_input_length' => 65535,
        'skip_fields'      => ['password', 'password_confirmation', '_token', 'content', 'description', 'body'],
    ],
    'uploads' => [
        'allowed_image_types' => ['image/jpeg', 'image/png', 'image/gif', 'image/webp'],
        'allowed_video_types' => ['video/mp4', 'video/webm', 'video/ogg'],
        'allowed_doc_types'   => ['application/pdf', 'application/zip', 'text/plain'],
        'max_image_size_mb'   => 5,
        'max_video_size_mb'   => 500,
        'max_doc_size_mb'     => 50,
        'blocked_extensions'  => ['php', 'php3', 'php4', 'php5', 'phtml', 'exe', 'sh', 'bat', 'cmd', 'js', 'html', 'htm'],
    ],
    'session' => ['regenerate_on_login' => true, 'invalidate_on_logout' => true, 'encrypt' => true, 'same_site' => 'strict', 'http_only' => true, 'secure' => env('SESSION_SECURE_COOKIE', false)],
    'password' => ['min_length' => 8, 'require_uppercase' => false, 'require_number' => false, 'require_special' => false, 'bcrypt_cost' => 12],
];
